# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a1d165e12a2bc249fdd588b275f670198835b689324af3b36e8b9ab4fe246ec80c97c1cb6d3ba495c7d214a06eb3285f25081ce6d307d520a9c0a6bdd892875
  aws_bucket: sapphire
  aws_region: us-east-1
  base_url: localhost:3030

test:
  secret_key_base: 48d66320aed438a4297c67b5b849010cfe7fa46ef27dcb0c8e7a761802f618ac34645e95add959bba8e65f369f76723f49ecb6db00e4cfbf7613f204838e0c8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0a1d165e12a2bc249fdd588b275f670198835b689324af3b36e8b9ab4fe246ec80c97c1cb6d3ba495c7d214a06eb3285f25081ce6d307d520a9c0a6bdd892875
  aws_bucket: sapphire
  aws_region: us-east-1
  base_url: 192.168.50.166:80
